workspace(name = "asylo_hello_world")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Asylo
http_archive(
  name = "com_google_asylo",
  urls = ["https://github.com/google/asylo/archive/v0.5.2.tar.gz"],
  strip_prefix = "asylo-0.5.2",
)


load("@com_google_asylo//asylo/bazel:asylo_deps.bzl", "asylo_deps")
asylo_deps()

load("@com_google_asylo//asylo/bazel:sgx_deps.bzl", "sgx_deps")
sgx_deps()
