# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tls-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
      - TLS.YOURDOMAIN.COM
      secretName: tls-cert
  rules:
    - host: TLS.YOURDOMAIN.COM
      http:
        paths:
          - backend:
              serviceName: tls-service
              servicePort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: tls-service
  labels:
    app: tls-app
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 5678
  selector:
    app: tls-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tls-deployment
spec:
  selector:
    matchLabels:
      app: tls-app
  replicas: 1
  template:
    metadata:
      labels:
        app: tls-app
    spec:
      containers:
        - name: tls
          image: hashicorp/http-echo
          args:
            - "-text=echo1"
          imagePullPolicy: Always
          ports:
            - containerPort: 5678
      imagePullSecrets:
        - name: regcred
